/**
 * Activity Types - Centralized definitions for all loggable activities
 *
 * Naming convention: CATEGORY_ACTION_DETAIL
 * Examples: AUTH_GOOGLE_LOGIN_SUCCESS, JOIN_GROUP_REQUEST_SUBMITTED
 */

export const ActivityTypes = {
  // =========================================================================
  // AUTH - Authentication Events
  // =========================================================================
  AUTH: {
    // Google OAuth
    GOOGLE_LOGIN_INITIATED: 'AUTH_GOOGLE_LOGIN_INITIATED',
    GOOGLE_LOGIN_SUCCESS: 'AUTH_GOOGLE_LOGIN_SUCCESS',
    GOOGLE_LOGIN_FAILED: 'AUTH_GOOGLE_LOGIN_FAILED',
    GOOGLE_CALLBACK_ERROR: 'AUTH_GOOGLE_CALLBACK_ERROR',

    // Auth code exchange (iOS)
    AUTH_CODE_EXCHANGE_SUCCESS: 'AUTH_CODE_EXCHANGE_SUCCESS',
    AUTH_CODE_EXCHANGE_FAILED: 'AUTH_CODE_EXCHANGE_FAILED',
    AUTH_CODE_EXPIRED: 'AUTH_CODE_EXPIRED',

    // Phone verification
    PHONE_VERIFICATION_SENT: 'AUTH_PHONE_VERIFICATION_SENT',
    PHONE_VERIFICATION_SEND_FAILED: 'AUTH_PHONE_VERIFICATION_SEND_FAILED',
    PHONE_VERIFICATION_SUCCESS: 'AUTH_PHONE_VERIFICATION_SUCCESS',
    PHONE_VERIFICATION_FAILED: 'AUTH_PHONE_VERIFICATION_FAILED',
    PHONE_VERIFICATION_INVALID_CODE: 'AUTH_PHONE_VERIFICATION_INVALID_CODE',

    // Member authentication (client-originated)
    MEMBER_LOGIN_PHONE_SUBMITTED: 'AUTH_MEMBER_LOGIN_PHONE_SUBMITTED',
    MEMBER_LOGIN_VERIFIED: 'AUTH_MEMBER_LOGIN_VERIFIED',
    MEMBER_LOGIN_SUCCESS: 'AUTH_MEMBER_LOGIN_SUCCESS',
    MEMBER_LOGIN_FAILED: 'AUTH_MEMBER_LOGIN_FAILED',
    MEMBER_SESSION_CHECK: 'AUTH_MEMBER_SESSION_CHECK',
    MEMBER_SESSION_CHECK_FAILED: 'AUTH_SESSION_CHECK_FAILED',
    MEMBER_LOGOUT: 'AUTH_MEMBER_LOGOUT',

    // Admin OAuth (client-originated)
    ADMIN_OAUTH_INITIATED: 'AUTH_ADMIN_OAUTH_INITIATED',
    ADMIN_OAUTH_COMPLETED: 'AUTH_ADMIN_OAUTH_COMPLETED',
    ADMIN_OAUTH_FAILED: 'AUTH_ADMIN_OAUTH_FAILED',

    // User session
    USER_SESSION_CHECK: 'AUTH_USER_SESSION_CHECK',
    USER_LOGOUT: 'AUTH_USER_LOGOUT',

    // Google profile linking (Member accounts - NOT login)
    GOOGLE_PROFILE_LINK_INITIATED: 'AUTH_GOOGLE_PROFILE_LINK_INITIATED',
    GOOGLE_PROFILE_LINK_SUCCESS: 'AUTH_GOOGLE_PROFILE_LINK_SUCCESS',
    GOOGLE_PROFILE_LINK_FAILED: 'AUTH_GOOGLE_PROFILE_LINK_FAILED',
    GOOGLE_PROFILE_ALREADY_LINKED: 'AUTH_GOOGLE_PROFILE_ALREADY_LINKED',
    GOOGLE_PROFILE_UNLINKED: 'AUTH_GOOGLE_PROFILE_UNLINKED',
    GOOGLE_PROFILE_SYNCED: 'AUTH_GOOGLE_PROFILE_SYNCED',

    // iOS app access control
    IOS_ACCESS_DENIED: 'AUTH_IOS_ACCESS_DENIED',

    // Account linking (bidirectional User <-> Member)
    ACCOUNT_LINK_PHONE_SEND: 'AUTH_ACCOUNT_LINK_PHONE_SEND',
    ACCOUNT_LINK_PHONE_SEND_FAILED: 'AUTH_ACCOUNT_LINK_PHONE_SEND_FAILED',
    ACCOUNT_LINK_PHONE_VERIFY: 'AUTH_ACCOUNT_LINK_PHONE_VERIFY',
    ACCOUNT_LINK_PHONE_VERIFY_FAILED: 'AUTH_ACCOUNT_LINK_PHONE_VERIFY_FAILED',
    ACCOUNT_LINK_GOOGLE_INITIATED: 'AUTH_ACCOUNT_LINK_GOOGLE_INITIATED',
    ACCOUNT_LINK_SUCCESS: 'AUTH_ACCOUNT_LINK_SUCCESS',
    ACCOUNT_LINK_FAILED: 'AUTH_ACCOUNT_LINK_FAILED',
    ACCOUNT_LINK_RELINKED: 'AUTH_ACCOUNT_LINK_RELINKED',
    ACCOUNT_UNLINK_SUCCESS: 'AUTH_ACCOUNT_UNLINK_SUCCESS',
    ACCOUNT_UNLINK_FAILED: 'AUTH_ACCOUNT_UNLINK_FAILED',
  },

  // =========================================================================
  // JOIN - Join/Membership Events
  // =========================================================================
  JOIN: {
    // Client-originated group join flow (step-by-step)
    GROUP_URL_ACCESSED: 'JOIN_GROUP_URL_ACCESSED',
    GROUP_INFO_VIEWED: 'JOIN_GROUP_INFO_VIEWED',
    GROUP_OPTIN_SUBMITTED: 'JOIN_GROUP_OPTIN_SUBMITTED',
    GROUP_PROFILE_SUBMITTED: 'JOIN_GROUP_PROFILE_SUBMITTED',
    GROUP_PHONE_SUBMITTED: 'JOIN_GROUP_PHONE_SUBMITTED',
    GROUP_PHONE_FAILED: 'JOIN_GROUP_PHONE_FAILED',
    GROUP_VERIFY_SUBMITTED: 'JOIN_GROUP_VERIFY_SUBMITTED',
    GROUP_VERIFY_FAILED: 'JOIN_GROUP_VERIFY_FAILED',
    GROUP_CONFIRMED: 'JOIN_GROUP_CONFIRMED',

    // Client-originated event join flow
    EVENT_URL_ACCESSED: 'JOIN_EVENT_URL_ACCESSED',
    EVENT_OPTIN_SUBMITTED: 'JOIN_EVENT_OPTIN_SUBMITTED',
    EVENT_PHONE_SUBMITTED: 'JOIN_EVENT_PHONE_SUBMITTED',
    EVENT_PHONE_FAILED: 'JOIN_EVENT_PHONE_FAILED',
    EVENT_VERIFY_SUBMITTED: 'JOIN_EVENT_VERIFY_SUBMITTED',
    EVENT_VERIFY_FAILED: 'JOIN_EVENT_VERIFY_FAILED',
    EVENT_CONFIRMED: 'JOIN_EVENT_CONFIRMED',

    // Client-originated study join flow
    STUDY_URL_ACCESSED: 'JOIN_STUDY_URL_ACCESSED',
    STUDY_OPTIN_SUBMITTED: 'JOIN_STUDY_OPTIN_SUBMITTED',
    STUDY_PHONE_SUBMITTED: 'JOIN_STUDY_PHONE_SUBMITTED',
    STUDY_PHONE_FAILED: 'JOIN_STUDY_PHONE_FAILED',
    STUDY_VERIFY_SUBMITTED: 'JOIN_STUDY_VERIFY_SUBMITTED',
    STUDY_VERIFY_FAILED: 'JOIN_STUDY_VERIFY_FAILED',
    STUDY_CONFIRMED: 'JOIN_STUDY_CONFIRMED',

    // Server-originated group joins
    GROUP_REQUEST_SUBMITTED: 'JOIN_GROUP_REQUEST_SUBMITTED',
    GROUP_REQUEST_APPROVED: 'JOIN_GROUP_REQUEST_APPROVED',
    GROUP_REQUEST_REJECTED: 'JOIN_GROUP_REQUEST_REJECTED',
    GROUP_REQUEST_DUPLICATE: 'JOIN_GROUP_REQUEST_DUPLICATE',
    GROUP_ALREADY_MEMBER: 'JOIN_GROUP_ALREADY_MEMBER',
    GROUP_CODE_LOOKUP: 'JOIN_GROUP_CODE_LOOKUP',
    GROUP_CODE_NOT_FOUND: 'JOIN_GROUP_CODE_NOT_FOUND',

    // Invite-based joins
    INVITE_ACCEPTED: 'JOIN_INVITE_ACCEPTED',
    INVITE_FAILED: 'JOIN_INVITE_FAILED',
    INVITE_EXPIRED: 'JOIN_INVITE_EXPIRED',
    INVITE_NOT_FOUND: 'JOIN_INVITE_NOT_FOUND',

    // Event RSVPs
    EVENT_RSVP_SUBMITTED: 'JOIN_EVENT_RSVP_SUBMITTED',
    EVENT_RSVP_UPDATED: 'JOIN_EVENT_RSVP_UPDATED',
    EVENT_RSVP_FAILED: 'JOIN_EVENT_RSVP_FAILED',
    EVENT_PUBLIC_RSVP: 'JOIN_EVENT_PUBLIC_RSVP',
    EVENT_MEMBER_INVITE: 'JOIN_EVENT_MEMBER_INVITE',

    // Study enrollments
    ENROLLMENT_CREATED: 'JOIN_ENROLLMENT_CREATED',
    ENROLLMENT_FAILED: 'JOIN_ENROLLMENT_FAILED',
  },

  // =========================================================================
  // ACCESS - Resource Access Events (optional future expansion)
  // =========================================================================
  ACCESS: {
    LESSON_VIEWED: 'ACCESS_LESSON_VIEWED',
    LESSON_CODE_LOOKUP: 'ACCESS_LESSON_CODE_LOOKUP',
    PROFILE_VIEWED: 'ACCESS_PROFILE_VIEWED',

    // Client-originated access events
    DASHBOARD_VIEWED: 'ACCESS_DASHBOARD_VIEWED',
    GROUP_HOME_VIEWED: 'ACCESS_GROUP_HOME_VIEWED',
    STUDY_HOME_VIEWED: 'ACCESS_STUDY_HOME_VIEWED',
    LESSON_STARTED: 'ACCESS_LESSON_STARTED',
    NOTE_SUBMITTED: 'ACCESS_NOTE_SUBMITTED',
    VIDEO_PROGRESS_SAVED: 'ACCESS_VIDEO_PROGRESS_SAVED',
    PROFILE_UPDATED: 'ACCESS_PROFILE_UPDATED',
    AVATAR_UPLOADED: 'ACCESS_AVATAR_UPLOADED',
    API_ERROR: 'ACCESS_API_ERROR',
  },
} as const

// Type helpers for TypeScript
export type ActivityCategory = keyof typeof ActivityTypes
export type AuthActivityType =
  (typeof ActivityTypes.AUTH)[keyof typeof ActivityTypes.AUTH]
export type JoinActivityType =
  (typeof ActivityTypes.JOIN)[keyof typeof ActivityTypes.JOIN]
export type AccessActivityType =
  (typeof ActivityTypes.ACCESS)[keyof typeof ActivityTypes.ACCESS]
export type AnyActivityType =
  | AuthActivityType
  | JoinActivityType
  | AccessActivityType
