//
//  Typography.swift
//  MakeReady
//
//  Centralized font tokens (audit Phase 5.4). One token per (size,
//  weight) combination IN USE, at the app's current fixed sizes —
//  generated mechanically from the call sites, so rendering is
//  byte-identical to the raw .system(size:) calls they replaced.
//
//  Names are systematic (s13Semibold = 13pt semibold) rather than
//  semantic on purpose: mapping sizes to roles (title/body/caption) and
//  enabling Dynamic Type (relativeTo:) are design decisions parked as
//  Decision Point C — when that lands, THIS is the only file to edit.
//
//  New code: use a Typography token (the SwiftLint gate blocks raw
//  .system(size:) outside this file). Need a new combination? Add the
//  token here. Site counts below are from the 2026-06-11 migration.
//

import SwiftUI

enum Typography {
    /// 8pt bold (3 sites)
    static let s8Bold = Font.system(size: 8, weight: .bold)
    /// 9pt bold (2 sites)
    static let s9Bold = Font.system(size: 9, weight: .bold)
    /// 10pt regular (10 sites)
    static let s10 = Font.system(size: 10)
    /// 10pt medium (3 sites)
    static let s10Medium = Font.system(size: 10, weight: .medium)
    /// 10pt semibold (5 sites)
    static let s10Semibold = Font.system(size: 10, weight: .semibold)
    /// 10pt bold (8 sites)
    static let s10Bold = Font.system(size: 10, weight: .bold)
    /// 11pt regular (31 sites)
    static let s11 = Font.system(size: 11)
    /// 11pt medium (1 site)
    static let s11Medium = Font.system(size: 11, weight: .medium)
    /// 11pt semibold (6 sites)
    static let s11Semibold = Font.system(size: 11, weight: .semibold)
    /// 11pt bold (4 sites)
    static let s11Bold = Font.system(size: 11, weight: .bold)
    /// 12pt regular (69 sites)
    static let s12 = Font.system(size: 12)
    /// 12pt medium (9 sites)
    static let s12Medium = Font.system(size: 12, weight: .medium)
    /// 12pt semibold (14 sites)
    static let s12Semibold = Font.system(size: 12, weight: .semibold)
    /// 12pt bold (11 sites)
    static let s12Bold = Font.system(size: 12, weight: .bold)
    /// 13pt regular (68 sites)
    static let s13 = Font.system(size: 13)
    /// 13pt medium (10 sites)
    static let s13Medium = Font.system(size: 13, weight: .medium)
    /// 13pt medium monospaced (3 sites)
    static let s13MediumMono = Font.system(size: 13, weight: .medium, design: .monospaced)
    /// 13pt semibold (139 sites)
    static let s13Semibold = Font.system(size: 13, weight: .semibold)
    /// 13pt bold (7 sites)
    static let s13Bold = Font.system(size: 13, weight: .bold)
    /// 14pt regular (54 sites)
    static let s14 = Font.system(size: 14)
    /// 14pt medium (12 sites)
    static let s14Medium = Font.system(size: 14, weight: .medium)
    /// 14pt semibold (20 sites)
    static let s14Semibold = Font.system(size: 14, weight: .semibold)
    /// 14pt bold (5 sites)
    static let s14Bold = Font.system(size: 14, weight: .bold)
    /// 15pt regular (66 sites)
    static let s15 = Font.system(size: 15)
    /// 15pt medium (7 sites)
    static let s15Medium = Font.system(size: 15, weight: .medium)
    /// 15pt semibold (20 sites)
    static let s15Semibold = Font.system(size: 15, weight: .semibold)
    /// 15pt bold (15 sites)
    static let s15Bold = Font.system(size: 15, weight: .bold)
    /// 16pt regular (17 sites)
    static let s16 = Font.system(size: 16)
    /// 16pt medium (2 sites)
    static let s16Medium = Font.system(size: 16, weight: .medium)
    /// 16pt semibold (11 sites)
    static let s16Semibold = Font.system(size: 16, weight: .semibold)
    /// 16pt bold (10 sites)
    static let s16Bold = Font.system(size: 16, weight: .bold)
    /// 17pt regular (59 sites)
    static let s17 = Font.system(size: 17)
    /// 17pt medium (10 sites)
    static let s17Medium = Font.system(size: 17, weight: .medium)
    /// 17pt semibold (37 sites)
    static let s17Semibold = Font.system(size: 17, weight: .semibold)
    /// 17pt bold (57 sites)
    static let s17Bold = Font.system(size: 17, weight: .bold)
    /// 18pt regular (11 sites)
    static let s18 = Font.system(size: 18)
    /// 18pt bold (3 sites)
    static let s18Bold = Font.system(size: 18, weight: .bold)
    /// 20pt regular (29 sites)
    static let s20 = Font.system(size: 20)
    /// 20pt medium (2 sites)
    static let s20Medium = Font.system(size: 20, weight: .medium)
    /// 20pt semibold (9 sites)
    static let s20Semibold = Font.system(size: 20, weight: .semibold)
    /// 20pt bold (18 sites)
    static let s20Bold = Font.system(size: 20, weight: .bold)
    /// 22pt regular (8 sites)
    static let s22 = Font.system(size: 22)
    /// 22pt bold (4 sites)
    static let s22Bold = Font.system(size: 22, weight: .bold)
    /// 24pt regular (18 sites)
    static let s24 = Font.system(size: 24)
    /// 24pt medium (1 site)
    static let s24Medium = Font.system(size: 24, weight: .medium)
    /// 24pt bold (10 sites)
    static let s24Bold = Font.system(size: 24, weight: .bold)
    /// 28pt regular (8 sites)
    static let s28 = Font.system(size: 28)
    /// 28pt bold (3 sites)
    static let s28Bold = Font.system(size: 28, weight: .bold)
    /// 32pt regular (16 sites)
    static let s32 = Font.system(size: 32)
    /// 32pt medium (1 site)
    static let s32Medium = Font.system(size: 32, weight: .medium)
    /// 32pt bold (2 sites)
    static let s32Bold = Font.system(size: 32, weight: .bold)
    /// 36pt light (1 site)
    static let s36Light = Font.system(size: 36, weight: .light)
    /// 36pt regular (7 sites)
    static let s36 = Font.system(size: 36)
    /// 40pt regular (19 sites)
    static let s40 = Font.system(size: 40)
    /// 40pt medium (1 site)
    static let s40Medium = Font.system(size: 40, weight: .medium)
    /// 48pt regular (14 sites)
    static let s48 = Font.system(size: 48)
    /// 48pt bold (1 site)
    static let s48Bold = Font.system(size: 48, weight: .bold)
    /// 60pt regular (3 sites)
    static let s60 = Font.system(size: 60)
    /// 64pt regular (1 site)
    static let s64 = Font.system(size: 64)
    /// 80pt bold (2 sites)
    static let s80Bold = Font.system(size: 80, weight: .bold)
    /// 180pt regular (2 sites)
    static let s180 = Font.system(size: 180)
}
