FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy prisma schema and generate client
COPY prisma ./prisma/
RUN npx prisma generate

# Copy source code
COPY . .

EXPOSE 3010

# Run migrations then start dev server
CMD npx prisma migrate deploy --schema=./prisma/schema.prisma && npm run dev
