-- Add 3 new system themes (centered-verse, star-wars, word-cascade)
-- and update existing 5 themes to v2 definitions with new interaction/animation fields.

-- ── Update existing themes to v2 ────────────────────────────────────────────

UPDATE "text_themes" SET
  "definition" = '{"version":2,"background":{"color":"#0a0a0f","image":null,"video":null,"overlay":null},"interaction":{"mode":"tap-to-advance","autoPlayDelay":null,"swipeAdvances":true,"showProgress":true,"progressStyle":"dots"},"typography":{"fontFamily":"''SF Pro Text'', -apple-system, sans-serif","fontSize":17,"color":"rgba(255,255,255,0.9)","lineHeight":1.6},"elements":{"h1":{"style":{"fontSize":32,"fontWeight":"bold","textAlign":"center","color":"#ffffff"},"enter":{"type":"fade","duration":800,"easing":"ease-out"},"exit":{"type":"fade","duration":400},"display":"fullscreen","align":"center"},"h2":{"style":{"fontSize":24,"fontWeight":"bold","textAlign":"center"},"enter":{"type":"fade","duration":600,"easing":"ease-out"},"exit":{"type":"fade","duration":300},"align":"center"},"p":{"style":{},"enter":{"type":"slide-up","duration":600,"easing":"ease-out"},"exit":{"type":"fade","duration":300}},"li":{"style":{},"enter":{"type":"slide-up","duration":500,"stagger":300,"easing":"ease-out"},"exit":{"type":"fade","duration":300}},"verse":{"style":{"fontSize":18,"lineHeight":1.8},"enter":{"type":"fade","duration":600,"stagger":300},"exit":{"type":"fade","duration":300}},"verse-number":{"style":{"fontSize":12,"opacity":0.5,"fontWeight":"bold"}},"verse-reference":{"style":{"fontSize":14,"textTransform":"uppercase","letterSpacing":2},"enter":{"type":"fade","duration":400},"align":"center"}},"sequences":[{"match":"h1","phase":"solo","pauseAfter":true},{"match":"h2","phase":"solo","pauseAfter":true},{"match":"li","phase":"group","stagger":300,"pauseAfter":true},{"match":"verse","phase":"group","stagger":300,"pauseAfter":true},{"match":"p","phase":"solo","pauseAfter":false}]}',
  "updatedAt" = now()
WHERE "slug" = 'dramatic-reveal' AND "isSystem" = true;

UPDATE "text_themes" SET
  "definition" = '{"version":2,"background":{"color":"#0d1117","image":null,"video":null,"overlay":null},"interaction":{"mode":"auto-play","autoPlayDelay":2000,"tapAdvances":true,"swipeAdvances":true,"showProgress":true,"progressStyle":"dots"},"typography":{"fontFamily":"''SF Pro Text'', -apple-system, sans-serif","fontSize":17,"color":"rgba(255,255,255,0.85)","lineHeight":1.7},"elements":{"h1":{"style":{"fontSize":28,"fontWeight":"bold","color":"#ffffff"},"enter":{"type":"fade","duration":800,"easing":"ease-out"},"exit":null},"h2":{"style":{"fontSize":22,"fontWeight":"bold"},"enter":{"type":"fade","duration":700,"easing":"ease-out"},"exit":null},"p":{"style":{},"enter":{"type":"fade","duration":800,"easing":"ease-out"},"exit":null},"li":{"style":{},"enter":{"type":"fade","duration":600,"stagger":400,"easing":"ease-out"},"exit":null},"verse":{"style":{"fontSize":18,"lineHeight":1.8},"enter":{"type":"fade","duration":800,"stagger":400},"exit":null},"verse-number":{"style":{"fontSize":12,"opacity":0.4,"fontWeight":"bold"}},"verse-reference":{"style":{"fontSize":13,"textTransform":"uppercase","letterSpacing":1.5,"opacity":0.7},"enter":{"type":"fade","duration":500}}},"sequences":[{"match":"h1","phase":"solo","pauseAfter":false},{"match":"h2","phase":"solo","pauseAfter":false},{"match":"li","phase":"group","stagger":400,"pauseAfter":false},{"match":"verse","phase":"group","stagger":400,"pauseAfter":false},{"match":"p","phase":"solo","pauseAfter":false}]}',
  "updatedAt" = now()
WHERE "slug" = 'gentle-fade' AND "isSystem" = true;

UPDATE "text_themes" SET
  "definition" = '{"version":2,"background":{"color":"#1a1a2e","image":null,"video":null,"overlay":"linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)"},"interaction":{"mode":"tap-to-advance","autoPlayDelay":null,"swipeAdvances":true,"showProgress":true,"progressStyle":"dots"},"typography":{"fontFamily":"''SF Pro Text'', -apple-system, sans-serif","fontSize":17,"color":"rgba(255,255,255,0.95)","lineHeight":1.5},"elements":{"h1":{"style":{"fontSize":36,"fontWeight":"bold","color":"#ffffff"},"enter":{"type":"spring","duration":700,"easing":{"type":"spring","stiffness":300,"damping":12}},"exit":{"type":"slide-left","duration":400}},"h2":{"style":{"fontSize":26,"fontWeight":"bold"},"enter":{"type":"slide-right","duration":500,"easing":"ease-out"},"exit":{"type":"slide-left","duration":300}},"p":{"style":{},"enter":{"type":"slide-right","duration":500,"easing":"ease-out"},"exit":{"type":"slide-left","duration":300}},"li":{"style":{},"enter":{"type":"slide-up","duration":400,"easing":"ease-out"},"exit":{"type":"slide-left","duration":300}},"verse":{"style":{"fontSize":18,"lineHeight":1.8},"enter":{"type":"clip-reveal","duration":600},"exit":{"type":"fade","duration":300}},"verse-number":{"style":{"fontSize":12,"opacity":0.5,"fontWeight":"bold"}},"verse-reference":{"style":{"fontSize":14,"textTransform":"uppercase","letterSpacing":2},"enter":{"type":"clip-reveal","duration":500}}},"sequences":[{"match":"h1","phase":"solo","pauseAfter":true},{"match":"h2","phase":"solo","pauseAfter":true},{"match":"li","phase":"group","pauseAfter":true},{"match":"verse","phase":"group","stagger":200,"pauseAfter":true},{"match":"p","phase":"solo","pauseAfter":false}]}',
  "updatedAt" = now()
WHERE "slug" = 'bold-slide' AND "isSystem" = true;

UPDATE "text_themes" SET
  "definition" = '{"version":2,"background":{"color":"#1c1210","image":null,"video":null,"overlay":"rgba(28,18,16,0.6)"},"interaction":{"mode":"auto-play","autoPlayDelay":3000,"tapAdvances":true,"swipeAdvances":true,"showProgress":true,"progressStyle":"dots"},"typography":{"fontFamily":"''Georgia'', ''Times New Roman'', serif","fontSize":18,"color":"#faf0e6","lineHeight":1.8},"elements":{"h1":{"style":{"fontSize":30,"fontWeight":"bold","color":"#f5deb3","textAlign":"center"},"enter":{"type":"blur","duration":1000,"easing":"ease-out"},"exit":{"type":"fade","duration":500},"align":"center"},"h2":{"style":{"fontSize":24,"fontWeight":"bold","color":"#f5deb3"},"enter":{"type":"fade","duration":800,"easing":"ease-out"},"exit":{"type":"fade","duration":400}},"p":{"style":{"color":"#faf0e6"},"enter":{"type":"fade","duration":900,"easing":"ease-out"},"exit":{"type":"fade","duration":400}},"li":{"style":{"color":"#faf0e6"},"enter":{"type":"fade","duration":700,"stagger":500,"easing":"ease-out"},"exit":{"type":"fade","duration":300}},"verse":{"style":{"fontSize":18,"lineHeight":1.9,"color":"#faf0e6"},"enter":{"type":"fade","duration":800,"stagger":400},"exit":{"type":"fade","duration":400}},"verse-number":{"style":{"fontSize":12,"color":"#f5deb3","fontWeight":"bold"}},"verse-reference":{"style":{"fontSize":13,"textTransform":"uppercase","letterSpacing":2,"color":"#f5deb3","opacity":0.8},"enter":{"type":"fade","duration":500}}},"sequences":[{"match":"h1","phase":"solo","pauseAfter":false},{"match":"h2","phase":"solo","pauseAfter":false},{"match":"li","phase":"group","stagger":500,"pauseAfter":false},{"match":"verse","phase":"group","stagger":400,"pauseAfter":false},{"match":"p","phase":"solo","pauseAfter":false}]}',
  "updatedAt" = now()
WHERE "slug" = 'firelight' AND "isSystem" = true;

UPDATE "text_themes" SET
  "definition" = '{"version":2,"background":{"color":"#111111","image":null,"video":null,"overlay":null},"interaction":{"mode":"auto-play","autoPlayDelay":500,"tapAdvances":true,"swipeAdvances":true,"showProgress":false},"typography":{"fontFamily":"''Courier New'', ''Courier'', monospace","fontSize":17,"color":"rgba(255,255,255,0.9)","lineHeight":1.6},"elements":{"h1":{"style":{"fontSize":28,"fontWeight":"bold","fontFamily":"''Courier New'', monospace"},"enter":{"type":"typewriter","duration":1500,"easing":"linear"},"exit":{"type":"fade","duration":300}},"h2":{"style":{"fontSize":22,"fontWeight":"bold","fontFamily":"''Courier New'', monospace"},"enter":{"type":"typewriter","duration":1200,"easing":"linear"},"exit":{"type":"fade","duration":300}},"p":{"style":{"fontFamily":"''Courier New'', monospace"},"enter":{"type":"typewriter","duration":1200,"easing":"linear"},"exit":{"type":"fade","duration":300}},"li":{"style":{"fontFamily":"''Courier New'', monospace"},"enter":{"type":"typewriter","duration":1000,"stagger":200,"easing":"linear"},"exit":{"type":"fade","duration":300}},"verse":{"style":{"fontSize":17,"lineHeight":1.7,"fontFamily":"''SF Pro Text'', -apple-system, sans-serif"},"enter":{"type":"fade","duration":600,"stagger":300},"exit":{"type":"fade","duration":300}},"verse-number":{"style":{"fontSize":12,"opacity":0.5,"fontWeight":"bold"}},"verse-reference":{"style":{"fontSize":13,"textTransform":"uppercase","letterSpacing":1},"enter":{"type":"fade","duration":400}}},"sequences":[{"match":"h1","phase":"solo","pauseAfter":true},{"match":"h2","phase":"solo","pauseAfter":true},{"match":"li","phase":"group","stagger":200,"pauseAfter":true},{"match":"verse","phase":"group","stagger":300,"pauseAfter":true},{"match":"p","phase":"solo","pauseAfter":false}]}',
  "updatedAt" = now()
WHERE "slug" = 'typewriter' AND "isSystem" = true;

-- ── Insert 3 new themes ───────────────────────────────────────────────────────

INSERT INTO "text_themes" ("id", "name", "slug", "description", "definition", "isSystem", "isActive", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'Centered Verse', 'centered-verse', 'Full-screen centered presentation — perfect for single verses and key phrases', '{"version":2,"background":{"color":"#070b14","image":null,"video":null,"overlay":null},"interaction":{"mode":"tap-to-advance","autoPlayDelay":null,"swipeAdvances":true,"showProgress":true,"progressStyle":"dots"},"typography":{"fontFamily":"''Georgia'', ''Times New Roman'', serif","fontSize":20,"color":"rgba(255,255,255,0.95)","lineHeight":1.7},"elements":{"h1":{"style":{"fontSize":28,"fontWeight":"700","color":"#ffffff","textAlign":"center"},"enter":{"type":"fade","duration":900,"easing":"ease-out"},"display":"centered","align":"center","width":"85%"},"h2":{"style":{"fontSize":22,"fontWeight":"600","color":"#ffffff","textAlign":"center"},"enter":{"type":"fade","duration":700,"easing":"ease-out"},"display":"centered","align":"center"},"p":{"style":{"textAlign":"center"},"enter":{"type":"fade","duration":700,"easing":"ease-out"},"display":"centered","align":"center","width":"85%"},"li":{"style":{"textAlign":"center"},"enter":{"type":"fade","duration":600,"stagger":350,"easing":"ease-out"},"align":"center"},"verse":{"style":{"fontSize":20,"lineHeight":1.8,"textAlign":"center"},"enter":{"type":"fade","duration":800,"stagger":500},"display":"centered","align":"center"},"verse-number":{"style":{"fontSize":11,"opacity":0.45,"fontWeight":"bold"}},"verse-reference":{"style":{"fontSize":13,"textTransform":"uppercase","letterSpacing":2.5,"opacity":0.6,"textAlign":"center"},"enter":{"type":"fade","duration":500},"align":"center"}},"sequences":[{"match":"h1","phase":"solo","pauseAfter":true},{"match":"h2","phase":"solo","pauseAfter":true},{"match":"verse-reference","phase":"solo","pauseAfter":false},{"match":"verse","phase":"solo","pauseAfter":true},{"match":"li","phase":"solo","stagger":350,"pauseAfter":true},{"match":"p","phase":"solo","pauseAfter":true}]}', true, true, now(), now()),

  (gen_random_uuid(), 'Star Wars', 'star-wars', 'Continuous scroll-up crawl — classic perspective-tilt text roll', '{"version":2,"background":{"color":"#000005","image":null,"video":null,"overlay":null},"interaction":{"mode":"auto-play","autoPlayDelay":500,"tapAdvances":true,"swipeAdvances":false,"showProgress":false},"typography":{"fontFamily":"''Georgia'', serif","fontSize":24,"color":"#ffe81f","lineHeight":1.4},"elements":{"h1":{"style":{"fontSize":26,"fontWeight":"bold","color":"#ffe81f","textAlign":"center","textTransform":"uppercase","letterSpacing":3},"enter":{"type":"scroll-up","duration":15000},"display":"fullscreen","align":"center"},"h2":{"style":{"fontSize":22,"fontWeight":"bold","color":"#ffe81f","textTransform":"uppercase","letterSpacing":2},"enter":{"type":"scroll-up","duration":12000},"align":"center"},"p":{"style":{"color":"#ffe81f","textAlign":"center"},"enter":{"type":"scroll-up","duration":10000},"align":"center"},"li":{"style":{"color":"#ffe81f","textAlign":"center"},"enter":{"type":"scroll-up","duration":10000},"align":"center"},"verse":{"style":{"fontSize":18,"color":"#ffe81f","textAlign":"center"},"enter":{"type":"scroll-up","duration":12000},"display":"fullscreen","align":"center"},"verse-number":{"style":{"fontSize":12,"opacity":0.5,"color":"#ffe81f"}},"verse-reference":{"style":{"fontSize":13,"color":"#ffe81f","textTransform":"uppercase","letterSpacing":3,"textAlign":"center"},"enter":{"type":"fade","duration":800},"align":"center"}},"sequences":[{"match":"h1","phase":"solo","pauseAfter":true,"minDisplayDuration":15000},{"match":"h2","phase":"solo","pauseAfter":true,"minDisplayDuration":12000},{"match":"verse-reference","phase":"solo","pauseAfter":false},{"match":"verse","phase":"solo","pauseAfter":true,"minDisplayDuration":12000},{"match":"p","phase":"solo","pauseAfter":true,"minDisplayDuration":10000},{"match":"li","phase":"group","pauseAfter":true,"minDisplayDuration":10000}]}', true, true, now(), now()),

  (gen_random_uuid(), 'Word Cascade', 'word-cascade', 'Words appear one by one — deliberate emphasis on each word', '{"version":2,"background":{"color":"#0f0f13","image":null,"video":null,"overlay":null},"interaction":{"mode":"auto-play","autoPlayDelay":800,"tapAdvances":true,"swipeAdvances":true,"showProgress":true,"progressStyle":"bar"},"typography":{"fontFamily":"''SF Pro Display'', -apple-system, sans-serif","fontSize":22,"color":"rgba(255,255,255,0.95)","lineHeight":1.5},"elements":{"h1":{"style":{"fontSize":30,"fontWeight":"700","textAlign":"center"},"enter":{"type":"word-by-word","duration":2000,"wordStagger":180},"display":"centered","align":"center"},"h2":{"style":{"fontSize":24,"fontWeight":"600"},"enter":{"type":"word-by-word","duration":1500,"wordStagger":160}},"p":{"style":{"fontSize":20},"enter":{"type":"word-by-word","duration":1200,"wordStagger":130}},"li":{"style":{},"enter":{"type":"word-by-word","duration":1000,"wordStagger":120},"exit":null},"verse":{"style":{"fontSize":20,"lineHeight":1.7},"enter":{"type":"word-by-word","duration":1500,"wordStagger":150}},"verse-number":{"style":{"fontSize":11,"opacity":0.4}},"verse-reference":{"style":{"fontSize":13,"textTransform":"uppercase","letterSpacing":1.5,"opacity":0.65},"enter":{"type":"fade","duration":500}}},"sequences":[{"match":"h1","phase":"solo","pauseAfter":true,"minDisplayDuration":2500},{"match":"h2","phase":"solo","pauseAfter":true,"minDisplayDuration":2000},{"match":"verse-reference","phase":"solo","pauseAfter":false},{"match":"verse","phase":"solo","pauseAfter":true,"minDisplayDuration":2500},{"match":"li","phase":"solo","pauseAfter":true,"minDisplayDuration":1800},{"match":"p","phase":"solo","pauseAfter":true,"minDisplayDuration":2000}]}', true, true, now(), now())

ON CONFLICT ("slug") DO NOTHING;
